feat: add restapi block
terraform-ibm-modules/terraform-ibm-icd-elasticsearch pull request #193
Opened 2024-06-14 10:14 UTC by Aayush-Abhyarthi

### Description

https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/145

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-06-17 09:26 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-17 21:19 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-18 06:34 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-18 07:02 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-18 08:42 UTC, daniel-butler-irl commented on main.tf
> +resource "restapi_object" "start_trained_model_deployment" {
It was my understanding that to interact with the database you need to use the database internal credentials not the IBM Cloud IAM credentials that seem to be used here. Not sure if this is related to the pipeline failure.

2024-06-18 13:19 UTC, rajatagarwal-ibm commented
@Aayush-Abhyarthi did you try to connect to the DB instance? You probably need DB credentials to connect to the DB instead of the IBM Cloud credentials, can you confirm, please?

2024-06-18 20:25 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-18 21:34 UTC, Aayush-Abhyarthi commented
I added the admin user name and password in the ES connection url for authentication. But we are not passing any password for the admin user through our module while testing and this is the reason the pipeline is failing.
Could we add a random password in the pr_test.go file for testing the DA..? similar to what postgresql does? [here](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/blob/eecc97a300b09cee1e04ad9c67d3898dc726da93/tests/pr_test.go#L102C6-L102C28)
@daniel-butler-irl @rajatagarwal-ibm

2024-06-19 08:19 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-19 10:03 UTC, daniel-butler-irl commented
The terraform is executed from the pipeline, I expect there are security rules set up blocking the traffic from the public internet. This is blocking your REST calls causing a timeout. @ocofaigh do we solve this anywhere else yet?

2024-06-20 13:20 UTC, ocofaigh requested changes
The test is failing because its trying to hit a private endpoint. You will need to update the test to run in schematics so you have access to the private endpoint

2024-06-20 13:20 UTC, ocofaigh commented on variables.tf
> +  description = "Set it to true to install and start the elser model"
elser model -> Elastic's Natural Language Processing model

Also Add this `[Learn more](https://cloud.ibm.com/docs/databases-for-elasticsearch?topic=databases-for-elasticsearch-elser-embeddings-elasticsearch)`

2024-06-20 13:20 UTC, ocofaigh commented on solutions/secure/version.tf
> +      version = ">= 1.19.1"
DAs should lock into exact provider version

2024-06-20 13:20 UTC, ocofaigh commented on solutions/secure/variables.tf
> +  description = "Set it to true to install and start the elser model"
same as previous comment on variable description update

Not sure this should default to `true` ?

2024-06-20 13:20 UTC, ocofaigh commented on modules/fscloud/variables.tf
> +  description = "Set it to true to install and start the elser model"
same as previous comment on variable description update

2024-06-20 13:20 UTC, ocofaigh commented on version.tf
> +      version = ">= 1.19.1"
please also update the time provider above it too

2024-06-21 11:51 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-25 20:53 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-25 21:28 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-25 22:30 UTC, Aayush-Abhyarthi commented
To enable elser model, "`platinum`" plan will have to be used. I did the changes in the DA to use the "`platinum`" plan. But the test is failing with the error - "`elasticsearchpl is not available on multitenant`"

2024-06-26 09:47 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-26 10:07 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-06-26 16:43 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-08-02 14:26 UTC, ocofaigh commented
This work was done in https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/pull/223
closing

2024-08-02 14:26 UTC, closed without merging