feat: support for elasticsearch 8.7
terraform-ibm-modules/terraform-ibm-icd-elasticsearch pull request #23
Opened 2023-10-05 09:24 UTC by rajatagarwal-ibm

### Description

* Supporting Elasticsearch 8.7 version.
* Removed EOL versions 7.9 and 7.10
* Updated tests accordingly.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-10-05 09:25 UTC, rajatagarwal-ibm commented
/run pipeline

2023-10-05 10:14 UTC, rajatagarwal-ibm commented
/run pipeline

2023-10-05 13:44 UTC, rajatagarwal-ibm commented
/run pipeline

2023-10-05 14:56 UTC, ocofaigh commented on version.tf
> +  required_version = "<= 1.5.5"
`>= 1.3.0, <= 1.5.5`

2023-10-05 14:59 UTC, ocofaigh commented on examples/complete/version.tf
> +  required_version = "<= 1.5.5"
`>= 1.3.0, <= 1.5.5`

2023-10-05 15:00 UTC, ocofaigh commented on examples/basic/version.tf
> +  required_version = "<= 1.5.5"
`>= 1.3.0, <= 1.5.5`

2023-10-05 15:03 UTC, ocofaigh requested changes
see comments

2023-10-05 15:03 UTC, rajatagarwal-ibm commented on tests/other_test.go
> +			"elasticsearch_version": "8.7", // test latest or untested version of the Elasticsearch
sounds good.

2023-10-05 15:04 UTC, rajatagarwal-ibm commented on tests/other_test.go
> +			"elasticsearch_version": "8.7", // test latest or untested version of the Elasticsearch
Perhaps it will take the default value from example/main

2023-10-05 15:10 UTC, rajatagarwal-ibm commented
/run pipeline

2023-10-05 15:48 UTC, rajatagarwal-ibm commented
/run pipeline

2023-10-06 09:04 UTC, ocofaigh requested changes
Hey @rajatagarwal-ibm sorry, turns out the BSL license is only coming in tf 1.6, so plese update the range to be `>= 1.3.0, < 1.6.0`

2023-10-06 09:38 UTC, rajatagarwal-ibm commented
/run pipeline

2023-10-06 09:44 UTC, rajatagarwal-ibm commented
/run pipeline

2023-10-06 10:26 UTC, ocofaigh approved these changes

2023-10-06 10:26 UTC, merged

2023-10-06 10:28 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: