feat: expose the ability to use default encryption keys in fscloud submodule + DA
terraform-ibm-modules/terraform-ibm-icd-elasticsearch pull request #330
Opened 2024-11-11 20:39 UTC by jor2

### Description

https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/320

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Expose the ability to use default encryption keys in fscloud submodule + DA

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-11-11 20:40 UTC, jor2 commented
based off this [pr](https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/521)

2024-11-11 20:41 UTC, jor2 commented
/run pipeline

2024-11-11 23:14 UTC, jor2 commented
Skipping upgrade tests, only seen this fail
````hcl
TestRunStandardUpgradeSolution 2024-11-11T20:49:28Z logger.go:66: │ Error: Value for undeclared variable
TestRunStandardUpgradeSolution 2024-11-11T20:49:28Z logger.go:66: │ 
TestRunStandardUpgradeSolution 2024-11-11T20:49:28Z logger.go:66: │ A variable named "provider_visibility" was assigned on the command line,
TestRunStandardUpgradeSolution 2024-11-11T20:49:28Z logger.go:66: │ but the root module does not declare a variable of that name. To use this
TestRunStandardUpgradeSolution 2024-11-11T20:49:28Z logger.go:66: │ value, add a "variable" block to the configuration.
TestRunStandardUpgradeSolution 2024-11-11T20:49:28Z logger.go:66: ╵
````

2024-11-11 23:14 UTC, jor2 commented
/run pipeline

2024-11-12 10:30 UTC, ocofaigh requested changes
some minor comments, and also please add the fix for https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/324 as discussed

2024-11-12 10:30 UTC, ocofaigh commented on tests/pr_test.go
> +		{Name: "provider_visibility", Value: "public", DataType: "string"},
no need to set to public in this test as schematics has access to private endpoints

2024-11-12 10:30 UTC, ocofaigh commented on modules/fscloud/variables.tf
> +  description = "The Hyper Protect Crypto Services (HPCS) or Key Protect root key CRN to use for encrypting the disk that holds deployment backups. There are region limitation for backup encryption.
region limitation -> region limitations (I fixed it in the postgres PR too :) )

2024-11-12 11:07 UTC, jor2 commented
/run pipeline

2024-11-12 11:24 UTC, jor2 commented
/run pipeline

2024-11-12 12:32 UTC, shemau submitted a review, later dismissed
LGTM. The restore/group changes look good to.

The schematics test failed.

2024-11-12 12:39 UTC, shemau commented
```hcl
 2024/11/12 11:49:21 Terraform apply |   CreateSecretGroupWithContext failed: request_id: '77e1104f-3b52-a9fb-5499-4adc6343bb1c' path: 'manage/v2/groups' operation: 'create' a secret group with name 'els-sr-da-secret-group' already exists. [secrets-manager.04126E]
```

There seems to be a test collision if/when tests run in parallel the prefix is missing.

2024-11-12 15:52 UTC, jor2 commented
/run pipeline

2024-11-12 17:09 UTC, ocofaigh commented
@jor2 Still the same issue:
```
2024/11/12 16:18:21 Terraform apply |   CreateSecretGroupWithContext failed: request_id: 'bb136db9-014a-1488-9abf-ff03e560f000' path: 'manage/v2/groups' operation: 'create' a secret group with name 'els-sr-da-secret-group' already exists. [secrets-manager.04126E]
```

Somewhere a prefix value is not being passed and hence the secret name is clashing. Can you try find where and ensure prefix is being used

2024-11-12 17:09 UTC, ocofaigh commented
Seems to be related to service credentials: `with module.secrets_manager_service_credentials[0].module.secret_groups["els-sr-da-secret-group"].ibm_sm_secret_group.secret_group,`

2024-11-12 17:26 UTC, ocofaigh commented
FYI, there was also a bug in https://github.com/terraform-ibm-modules/terraform-ibm-icd-postgresql/pull/521 - I'm working on a fix so you will need that fix too

2024-11-12 17:32 UTC, jor2 commented
> Seems to be related to service credentials: `with module.secrets_manager_service_credentials[0].module.secret_groups["els-sr-da-secret-group"].ibm_sm_secret_group.secret_group,`

its because of this, any reason for it? https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/blob/main/tests/pr_test.go#L154

2024-11-12 18:04 UTC, jor2 commented
/run pipeline

2024-11-12 18:31 UTC, ocofaigh commented
FYI, there is currently an outage that is impacting tests

2024-11-12 20:07 UTC, jor2 commented
/run pipeline

2024-11-13 17:01 UTC, jor2 commented
/run pipeline

2024-11-13 20:40 UTC, jor2 commented
/run pipeline

2024-11-13 22:20 UTC, jor2 commented
/run pipeline

2024-11-13 23:32 UTC, jor2 commented
/run pipeline

2024-11-14 10:45 UTC, ocofaigh approved these changes

2024-11-14 10:53 UTC, shemau approved these changes
LGTM

I focus on the restore/group logic and that is fine for now.

2024-11-14 11:04 UTC, merged

2024-11-14 11:05 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.22.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/releases/tag/v1.22.0)
- `v1.22.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: